sample_rate: 16000
compute_eval_loss: false
log_prediction: true
rnnt_reduction: mean_volume
skip_nan_grad: true
freeze_diar: true
spk_supervision_strategy: rttm
rttm_mix_prob: 0.5
shuffle_spk_mapping: true
binarize_diar_preds_threshold: null
model_defaults:
  enc_hidden: 1024
  pred_hidden: 640
  joint_hidden: 640
  num_speakers: 4
  spk_tar_all_zero: false
  num_sample_per_mel_frame: 160
  num_mel_frame_per_asr_frame: 8
train_ds:
  use_lhotse: true
  skip_missing_manifest_entries: true
  input_cfg: null
  manifest_filepath: null
  sample_rate: 16000
  batch_size: 36
  shuffle: true
  num_workers: 4
  pin_memory: true
  max_duration: 40
  min_duration: 0.1
  drop_last: true
  text_field: answer
  bucketing_strategy: fully_randomized
  defer_setup: true
  bucketing_batch_size: null
  bucket_buffer_size: 100000
  shuffle_buffer_size: 50000
  num_speakers: 4
  spk_tar_all_zero: false
  num_sample_per_mel_frame: 160
  num_mel_frame_per_asr_frame: 8
  shuffle_spk_mapping: true
  batch_duration: 1200
  quadratic_duration: 20
validation_ds:
  use_lhotse: true
  input_cfg: null
  manifest_filepath: null
  sample_rate: 16000
  batch_size: 16
  shuffle: false
  use_start_end_token: false
  num_workers: 4
  pin_memory: true
  text_field: answer
  num_speakers: 4
  spk_tar_all_zero: false
  num_sample_per_mel_frame: 160
  num_mel_frame_per_asr_frame: 8
  shuffle_spk_mapping: false
  max_cuts: 8
  use_bucketing: false
  batch_duration: 800
  bucket_buffer_size: 2000
  shuffle_buffer_size: 1000
test_ds:
  manifest_filepath: null
  sample_rate: 16000
  batch_size: 16
  shuffle: false
  use_start_end_token: false
  num_workers: 8
  pin_memory: true
  num_speakers: 4
  spk_tar_all_zero: false
  num_sample_per_mel_frame: 160
  num_mel_frame_per_asr_frame: 8
  shuffle_spk_mapping: false
tokenizer:
  dir: /tokenizer
  type: bpe
  model_path: nemo:24892724e6a249268d657127026e63fa_tokenizer.model
  vocab_path: nemo:7b8567de3831492ab928bdd52c00d8d4_vocab.txt
  spe_tokenizer_vocab: nemo:cbf746060d624629844ab4972b158b6c_tokenizer.vocab
  vocab_size: 1699
preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  sample_rate: 16000
  normalize: NA
  window_size: 0.025
  window_stride: 0.01
  window: hann
  features: 128
  n_fft: 512
  frame_splicing: 1
  dither: 1.0e-05
  pad_to: 0
  log: true
spec_augment:
  _target_: nemo.collections.asr.modules.SpectrogramAugmentation
  freq_masks: 2
  time_masks: 10
  freq_width: 27
  time_width: 0.05
encoder:
  _target_: nemo.collections.asr.modules.ConformerEncoder
  feat_in: 128
  feat_out: -1
  n_layers: 24
  d_model: 1024
  use_bias: false
  subsampling: dw_striding
  subsampling_factor: 8
  subsampling_conv_channels: 256
  causal_downsampling: true
  reduction: null
  reduction_position: null
  reduction_factor: 1
  ff_expansion_factor: 4
  self_attention_model: rel_pos
  n_heads: 8
  att_context_size:
  - - 70
    - 13
  - - 70
    - 6
  - - 70
    - 1
  - - 70
    - 0
  att_context_style: chunked_limited
  xscaling: false
  untie_biases: true
  pos_emb_max_len: 5000
  conv_kernel_size: 9
  conv_norm_type: layer_norm
  conv_context_size: causal
  dropout: 0.1
  dropout_pre_encoder: 0.1
  dropout_emb: 0.0
  dropout_att: 0.1
  stochastic_depth_drop_prob: 0.0
  stochastic_depth_mode: linear
  stochastic_depth_start_layer: 1
decoder:
  _target_: nemo.collections.asr.modules.RNNTDecoder
  normalization_mode: null
  random_state_sampling: false
  blank_as_pad: true
  prednet:
    pred_hidden: 640
    pred_rnn_layers: 2
    t_max: null
    dropout: 0.2
  vocab_size: 1700
joint:
  _target_: nemo.collections.asr.modules.RNNTJoint
  log_softmax: null
  preserve_memory: false
  fuse_loss_wer: true
  fused_batch_size: 16
  jointnet:
    joint_hidden: 640
    activation: relu
    dropout: 0.2
    encoder_hidden: 1024
    pred_hidden: 640
  num_classes: 1700
  vocabulary:
  - <unk>
  - ▁t
  - ▁th
  - ▁a
  - in
  - ▁the
  - re
  - ▁w
  - ▁o
  - ▁s
  - er
  - at
  - ou
  - nd
  - it
  - is
  - ▁h
  - ▁b
  - 'on'
  - ▁c
  - ing
  - en
  - ▁to
  - ▁m
  - ▁f
  - ▁p
  - or
  - an
  - es
  - ▁of
  - ▁d
  - ed
  - ll
  - ▁and
  - ▁I
  - ▁in
  - ▁l
  - ar
  - ▁y
  - ▁g
  - as
  - ▁you
  - om
  - ▁n
  - ic
  - ve
  - al
  - ion
  - us
  - ▁be
  - ow
  - le
  - ▁wh
  - ▁e
  - ot
  - ut
  - ▁it
  - ▁is
  - ▁we
  - ▁T
  - ▁re
  - et
  - ▁A
  - ent
  - ▁on
  - ▁ha
  - ay
  - ▁S
  - ct
  - ▁Th
  - ver
  - id
  - ig
  - im
  - ro
  - ▁for
  - ly
  - ▁he
  - ke
  - ld
  - se
  - st
  - ch
  - ▁st
  - all
  - ce
  - ur
  - ith
  - am
  - if
  - ir
  - ▁go
  - ▁u
  - ▁as
  - ▁was
  - ad
  - ▁W
  - ▁k
  - ▁an
  - ht
  - th
  - ▁r
  - ▁are
  - ere
  - ▁se
  - ▁do
  - ▁B
  - ▁so
  - ▁sh
  - ▁not
  - ▁li
  - od
  - ▁C
  - ust
  - ill
  - ight
  - ally
  - ▁And
  - ter
  - ▁or
  - ▁me
  - ▁M
  - ome
  - op
  - ▁at
  - il
  - ▁The
  - ould
  - ▁j
  - ant
  - ▁So
  - ▁H
  - ol
  - ain
  - ▁can
  - ▁de
  - ▁ne
  - ore
  - ▁con
  - ▁kn
  - ck
  - ul
  - ▁fr
  - ▁ab
  - ers
  - ess
  - ge
  - ▁pro
  - pe
  - ate
  - ▁su
  - ▁com
  - ▁but
  - ▁all
  - est
  - qu
  - ▁ex
  - ▁al
  - ra
  - ▁O
  - out
  - use
  - very
  - pp
  - ▁Y
  - ▁ch
  - ri
  - ist
  - ▁v
  - ▁lo
  - ment
  - art
  - ▁P
  - nt
  - ab
  - ▁one
  - ▁N
  - ive
  - ▁wor
  - ions
  - ort
  - ▁L
  - ▁by
  - ich
  - ▁my
  - ity
  - ok
  - ▁G
  - res
  - ▁up
  - un
  - um
  - ea
  - ind
  - and
  - ink
  - el
  - ▁D
  - em
  - ▁E
  - os
  - oug
  - ▁if
  - ca
  - ▁out
  - ▁int
  - ie
  - ▁F
  - ▁It
  - ▁his
  - ard
  - ▁had
  - ▁tr
  - her
  - our
  - ies
  - ake
  - ▁R
  - ▁We
  - ▁get
  - ▁don
  - ▁us
  - ak
  - ▁pl
  - ect
  - ure
  - ame
  - ast
  - ▁who
  - ack
  - ▁le
  - ▁sa
  - iv
  - ci
  - ide
  - ▁tim
  - ▁our
  - ound
  - ous
  - ▁co
  - ▁pe
  - ose
  - ud
  - ▁see
  - ough
  - ▁man
  - ▁qu
  - ▁You
  - so
  - ople
  - ▁Wh
  - ong
  - ap
  - ther
  - ▁J
  - are
  - ine
  - ▁say
  - ▁im
  - ▁But
  - ings
  - ▁has
  - ▁ag
  - ff
  - ▁her
  - itt
  - one
  - ▁en
  - ▁ar
  - ▁fe
  - ven
  - ▁any
  - ▁mo
  - reat
  - ag
  - ▁how
  - ▁cl
  - pt
  - ▁now
  - own
  - ber
  - ▁him
  - ▁act
  - hing
  - ice
  - ▁no
  - ans
  - iz
  - ▁fa
  - per
  - pl
  - ▁te
  - ▁ad
  - age
  - ree
  - ▁tw
  - ank
  - ▁He
  - ple
  - ite
  - ry
  - ▁U
  - ish
  - ire
  - ue
  - ▁In
  - ▁she
  - ble
  - cc
  - nder
  - ▁way
  - ▁pr
  - ear
  - ▁did
  - ▁po
  - eah
  - ▁un
  - omet
  - ence
  - ep
  - uch
  - ▁sp
  - ach
  - og
  - ance
  - able
  - iff
  - sel
  - ▁got
  - way
  - ▁gr
  - alk
  - ▁res
  - ated
  - irst
  - ick
  - ass
  - ▁two
  - ▁dis
  - ord
  - ▁pre
  - ount
  - ase
  - ip
  - ult
  - ical
  - orm
  - ary
  - ace
  - ▁spe
  - ▁Ch
  - ▁thr
  - ▁imp
  - int
  - ▁am
  - ▁off
  - act
  - ia
  - ▁ro
  - ress
  - ▁per
  - ▁fo
  - ▁br
  - ▁K
  - vel
  - ▁gu
  - ▁bo
  - ang
  - kay
  - ub
  - ign
  - ▁may
  - ving
  - ces
  - ens
  - cl
  - ▁lot
  - ru
  - ade
  - ▁bet
  - ▁bl
  - ▁let
  - fore
  - co
  - ild
  - ning
  - xt
  - ile
  - ark
  - self
  - ▁app
  - ory
  - du
  - ▁day
  - ▁St
  - ater
  - ▁use
  - ys
  - fter
  - ▁new
  - ious
  - ial
  - he
  - wn
  - ved
  - red
  - ▁fl
  - iss
  - ody
  - form
  - ian
  - tain
  - ▁bu
  - ▁V
  - ▁rec
  - ty
  - be
  - ▁sc
  - ors
  - vers
  - ▁put
  - ife
  - ▁If
  - we
  - te
  - ject
  - ath
  - ting
  - ▁rem
  - ▁acc
  - ull
  - ons
  - ▁ind
  - ▁ser
  - ▁ke
  - ates
  - ves
  - na
  - lic
  - ▁des
  - ▁its
  - ful
  - ents
  - erm
  - ac
  - ered
  - ise
  - ▁sy
  - urn
  - ▁em
  - oth
  - ual
  - ne
  - ward
  - ib
  - ▁try
  - ▁pos
  - nds
  - ft
  - get
  - ph
  - ▁ob
  - ady
  - igh
  - ood
  - ▁rel
  - ▁wr
  - ug
  - ears
  - ail
  - ▁Now
  - ▁bit
  - ng
  - ▁Oh
  - ▁hel
  - ange
  - ▁reg
  - ▁rep
  - ▁bel
  - ▁sm
  - ost
  - tern
  - gr
  - ▁own
  - ▁end
  - pect
  - ily
  - day
  - ied
  - ific
  - ower
  - ▁add
  - cess
  - ict
  - ible
  - ▁bas
  - ▁i
  - ▁op
  - cial
  - ular
  - ▁Be
  - ced
  - ▁too
  - ks
  - ew
  - mer
  - ▁ph
  - ob
  - ==
  - ▁la
  - ▁set
  - ▁min
  - ▁sub
  - ▁gen
  - atch
  - ..
  - ▁inv
  - ▁As
  - ▁nat
  - ▁sl
  - ▁num
  - av
  - ways
  - ▁God
  - stem
  - ▁ac
  - ▁att
  - ▁ev
  - ▁def
  - llow
  - ▁str
  - lect
  - ars
  - ▁cr
  - ▁Is
  - olog
  - les
  - oy
  - ▁ask
  - ▁inc
  - body
  - ▁ent
  - ▁pol
  - ness
  - ix
  - ▁why
  - onna
  - ▁ear
  - ▁tak
  - ▁Un
  - ited
  - mun
  - li
  - ute
  - ract
  - ▁dec
  - uro
  - ▁mak
  - ▁fin
  - ween
  - ▁No
  - arch
  - ▁bec
  - gan
  - old
  - cy
  - ▁big
  - ▁For
  - ren
  - als
  - und
  - ▁Al
  - ▁All
  - ss
  - ows
  - ▁mod
  - ock
  - ▁id
  - ism
  - cus
  - ▁gl
  - ably
  - ▁ass
  - ▁car
  - ata
  - ppen
  - led
  - ▁sim
  - ▁mon
  - ics
  - ▁giv
  - cept
  - ▁Mr
  - pan
  - ▁pub
  - ▁eff
  - ▁How
  - ps
  - vern
  - end
  - hip
  - iew
  - ope
  - ▁An
  - ▁She
  - ▁Com
  - ee
  - ures
  - ell
  - ouse
  - cond
  - king
  - oc
  - ues
  - ever
  - ▁To
  - clud
  - ▁ins
  - ▁exp
  - ▁old
  - ▁mem
  - ▁ref
  - ▁tra
  - ▁far
  - ave
  - rat
  - ▁sur
  - ruct
  - rib
  - duct
  - uff
  - ▁met
  - ▁sch
  - ince
  - ▁run
  - ense
  - ▁cle
  - ▁==
  - mon
  - ize
  - ▁ord
  - blem
  - tin
  - ▁Let
  - ner
  - ond
  - its
  - ▁cor
  - land
  - ▁cur
  - ▁Re
  - ▁bus
  - ▁uh
  - air
  - ote
  - ants
  - ason
  - ric
  - ▁el
  - ▁cer
  - nce
  - ▁fam
  - ▁cap
  - uck
  - ool
  - ried
  - ▁cou
  - ▁fun
  - ▁wom
  - ▁hum
  - ▁ty
  - ▁ap
  - ike
  - ▁few
  - oney
  - ▁inf
  - ont
  - ese
  - ook
  - gy
  - uth
  - ulat
  - ieve
  - ized
  - ross
  - ▁ple
  - ▁um
  - ▁val
  - ▁equ
  - ▁lea
  - ▁lar
  - ah
  - eral
  - ▁ed
  - ared
  - lish
  - arn
  - ds
  - esn
  - ▁iss
  - ▁ca
  - ted
  - ices
  - ▁wee
  - ash
  - ▁top
  - ten
  - up
  - ts
  - gin
  - con
  - ari
  - ▁opp
  - osed
  - ▁eas
  - ▁ext
  - gg
  - az
  - ▁Fr
  - ideo
  - izat
  - ▁men
  - ▁mom
  - ▁ret
  - tty
  - rist
  - ▁gra
  - alth
  - ef
  - ▁det
  - ax
  - ▁mat
  - chn
  - ern
  - peri
  - ▁bre
  - ▁Sh
  - sw
  - erat
  - ▁sit
  - ters
  - ale
  - man
  - ▁sol
  - ork
  - ▁adv
  - ety
  - ▁vis
  - ▁med
  - uc
  - less
  - ▁unt
  - gram
  - ets
  - ists
  - ▁ey
  - ▁col
  - imes
  - ▁law
  - ▁pri
  - sid
  - ▁On
  - ▁mot
  - ield
  - ▁Do
  - ▁At
  - ages
  - amp
  - ▁art
  - miss
  - ▁sk
  - alf
  - pr
  - ier
  - ▁beh
  - ▁Yes
  - ural
  - ime
  - ▁wa
  - oks
  - bers
  - ger
  - ient
  - ries
  - '...'
  - ▁che
  - ▁Br
  - ird
  - ▁Ar
  - ▁war
  - inat
  - ▁My
  - ital
  - wh
  - med
  - ▁pur
  - ully
  - ▁One
  - ▁rat
  - ines
  - ▁Of
  - io
  - ▁loc
  - ret
  - ctor
  - ▁leg
  - stit
  - ined
  - ught
  - ▁dur
  - ▁es
  - vent
  - aj
  - ▁bro
  - ▁saw
  - ▁sec
  - ream
  - ▁pop
  - reen
  - ▁Ind
  - els
  - ▁yet
  - ired
  - ▁sw
  - tro
  - oup
  - most
  - pean
  - eds
  - ush
  - oh
  - ▁Se
  - ▁tea
  - ann
  - ilit
  - err
  - pend
  - ton
  - ased
  - ▁aff
  - ▁mor
  - ▁dra
  - put
  - ▁dr
  - ins
  - uat
  - nect
  - cri
  - outh
  - ▁ra
  - ▁pay
  - ms
  - ▁av
  - bs
  - ling
  - ▁De
  - ▁Or
  - ove
  - ▁Can
  - ▁eng
  - ames
  - ided
  - ▁Go
  - mitt
  - ode
  - ▁cre
  - par
  - ides
  - pos
  - ▁fav
  - ▁air
  - ▁New
  - ▁bad
  - ▁six
  - vat
  - ▁pat
  - not
  - ▁di
  - rop
  - ral
  - orn
  - ▁par
  - cing
  - ▁aw
  - orts
  - ox
  - ▁yes
  - cuss
  - eng
  - ives
  - erms
  - ▁job
  - mand
  - ying
  - ▁occ
  - aps
  - ases
  - ▁Not
  - rent
  - ency
  - att
  - ised
  - vice
  - ▁Eng
  - ▁est
  - oked
  - ▁Q
  - iron
  - idd
  - me
  - unch
  - ane
  - ▁z
  - br
  - arts
  - ▁fat
  - ery
  - anks
  - ▁jo
  - ▁mar
  - aw
  - ott
  - ards
  - ▁oh
  - ians
  - ▁sci
  - row
  - unt
  - ury
  - ▁abs
  - ergy
  - ▁Z
  - ump
  - ▁Am
  - ened
  - angu
  - ▁Pro
  - icat
  - itch
  - ▁dri
  - iat
  - ▁
  - e
  - t
  - o
  - a
  - 'n'
  - i
  - s
  - r
  - h
  - l
  - d
  - u
  - c
  - m
  - 'y'
  - g
  - w
  - f
  - p
  - ','
  - .
  - b
  - v
  - k
  - ''''
  - I
  - T
  - A
  - S
  - x
  - W
  - j
  - C
  - B
  - M
  - '?'
  - H
  - O
  - '0'
  - P
  - q
  - 'Y'
  - 'N'
  - L
  - D
  - '1'
  - E
  - G
  - z
  - F
  - R
  - '-'
  - '2'
  - J
  - U
  - '9'
  - K
  - '5'
  - '3'
  - V
  - '='
  - '4'
  - '8'
  - '6'
  - '7'
  - '!'
  - '%'
  - ':'
  - Q
  - Z
  - $
  - X
  - '"'
  - '&'
  - '*'
  - /
  - £
  - +
  - €
  - _
  - ^
  - ¥
decoding:
  strategy: greedy_batch
  greedy:
    max_symbols: 10
  beam:
    beam_size: 2
    return_best_hypothesis: false
    score_norm: true
    tsd_max_sym_exp: 50
    alsd_max_target_len: 2.0
loss:
  loss_name: default
  warprnnt_numba_kwargs:
    fastemit_lambda: 0.0
    clamp: -1.0
optim:
  name: adamw
  lr: 2
  betas:
  - 0.9
  - 0.98
  weight_decay: 0.001
  sched:
    name: NoamAnnealing
    warmup_steps: 4000
    warmup_ratio: null
    min_lr: 1.0e-06
    d_model: 1024
spk_kernel_type: ff
spk_kernel_layers:
- 0
add_bg_spk_kernel: true
labels:
- <unk>
- ▁t
- ▁th
- ▁a
- in
- ▁the
- re
- ▁w
- ▁o
- ▁s
- er
- at
- ou
- nd
- it
- is
- ▁h
- ▁b
- 'on'
- ▁c
- ing
- en
- ▁to
- ▁m
- ▁f
- ▁p
- or
- an
- es
- ▁of
- ▁d
- ed
- ll
- ▁and
- ▁I
- ▁in
- ▁l
- ar
- ▁y
- ▁g
- as
- ▁you
- om
- ▁n
- ic
- ve
- al
- ion
- us
- ▁be
- ow
- le
- ▁wh
- ▁e
- ot
- ut
- ▁it
- ▁is
- ▁we
- ▁T
- ▁re
- et
- ▁A
- ent
- ▁on
- ▁ha
- ay
- ▁S
- ct
- ▁Th
- ver
- id
- ig
- im
- ro
- ▁for
- ly
- ▁he
- ke
- ld
- se
- st
- ch
- ▁st
- all
- ce
- ur
- ith
- am
- if
- ir
- ▁go
- ▁u
- ▁as
- ▁was
- ad
- ▁W
- ▁k
- ▁an
- ht
- th
- ▁r
- ▁are
- ere
- ▁se
- ▁do
- ▁B
- ▁so
- ▁sh
- ▁not
- ▁li
- od
- ▁C
- ust
- ill
- ight
- ally
- ▁And
- ter
- ▁or
- ▁me
- ▁M
- ome
- op
- ▁at
- il
- ▁The
- ould
- ▁j
- ant
- ▁So
- ▁H
- ol
- ain
- ▁can
- ▁de
- ▁ne
- ore
- ▁con
- ▁kn
- ck
- ul
- ▁fr
- ▁ab
- ers
- ess
- ge
- ▁pro
- pe
- ate
- ▁su
- ▁com
- ▁but
- ▁all
- est
- qu
- ▁ex
- ▁al
- ra
- ▁O
- out
- use
- very
- pp
- ▁Y
- ▁ch
- ri
- ist
- ▁v
- ▁lo
- ment
- art
- ▁P
- nt
- ab
- ▁one
- ▁N
- ive
- ▁wor
- ions
- ort
- ▁L
- ▁by
- ich
- ▁my
- ity
- ok
- ▁G
- res
- ▁up
- un
- um
- ea
- ind
- and
- ink
- el
- ▁D
- em
- ▁E
- os
- oug
- ▁if
- ca
- ▁out
- ▁int
- ie
- ▁F
- ▁It
- ▁his
- ard
- ▁had
- ▁tr
- her
- our
- ies
- ake
- ▁R
- ▁We
- ▁get
- ▁don
- ▁us
- ak
- ▁pl
- ect
- ure
- ame
- ast
- ▁who
- ack
- ▁le
- ▁sa
- iv
- ci
- ide
- ▁tim
- ▁our
- ound
- ous
- ▁co
- ▁pe
- ose
- ud
- ▁see
- ough
- ▁man
- ▁qu
- ▁You
- so
- ople
- ▁Wh
- ong
- ap
- ther
- ▁J
- are
- ine
- ▁say
- ▁im
- ▁But
- ings
- ▁has
- ▁ag
- ff
- ▁her
- itt
- one
- ▁en
- ▁ar
- ▁fe
- ven
- ▁any
- ▁mo
- reat
- ag
- ▁how
- ▁cl
- pt
- ▁now
- own
- ber
- ▁him
- ▁act
- hing
- ice
- ▁no
- ans
- iz
- ▁fa
- per
- pl
- ▁te
- ▁ad
- age
- ree
- ▁tw
- ank
- ▁He
- ple
- ite
- ry
- ▁U
- ish
- ire
- ue
- ▁In
- ▁she
- ble
- cc
- nder
- ▁way
- ▁pr
- ear
- ▁did
- ▁po
- eah
- ▁un
- omet
- ence
- ep
- uch
- ▁sp
- ach
- og
- ance
- able
- iff
- sel
- ▁got
- way
- ▁gr
- alk
- ▁res
- ated
- irst
- ick
- ass
- ▁two
- ▁dis
- ord
- ▁pre
- ount
- ase
- ip
- ult
- ical
- orm
- ary
- ace
- ▁spe
- ▁Ch
- ▁thr
- ▁imp
- int
- ▁am
- ▁off
- act
- ia
- ▁ro
- ress
- ▁per
- ▁fo
- ▁br
- ▁K
- vel
- ▁gu
- ▁bo
- ang
- kay
- ub
- ign
- ▁may
- ving
- ces
- ens
- cl
- ▁lot
- ru
- ade
- ▁bet
- ▁bl
- ▁let
- fore
- co
- ild
- ning
- xt
- ile
- ark
- self
- ▁app
- ory
- du
- ▁day
- ▁St
- ater
- ▁use
- ys
- fter
- ▁new
- ious
- ial
- he
- wn
- ved
- red
- ▁fl
- iss
- ody
- form
- ian
- tain
- ▁bu
- ▁V
- ▁rec
- ty
- be
- ▁sc
- ors
- vers
- ▁put
- ife
- ▁If
- we
- te
- ject
- ath
- ting
- ▁rem
- ▁acc
- ull
- ons
- ▁ind
- ▁ser
- ▁ke
- ates
- ves
- na
- lic
- ▁des
- ▁its
- ful
- ents
- erm
- ac
- ered
- ise
- ▁sy
- urn
- ▁em
- oth
- ual
- ne
- ward
- ib
- ▁try
- ▁pos
- nds
- ft
- get
- ph
- ▁ob
- ady
- igh
- ood
- ▁rel
- ▁wr
- ug
- ears
- ail
- ▁Now
- ▁bit
- ng
- ▁Oh
- ▁hel
- ange
- ▁reg
- ▁rep
- ▁bel
- ▁sm
- ost
- tern
- gr
- ▁own
- ▁end
- pect
- ily
- day
- ied
- ific
- ower
- ▁add
- cess
- ict
- ible
- ▁bas
- ▁i
- ▁op
- cial
- ular
- ▁Be
- ced
- ▁too
- ks
- ew
- mer
- ▁ph
- ob
- ==
- ▁la
- ▁set
- ▁min
- ▁sub
- ▁gen
- atch
- ..
- ▁inv
- ▁As
- ▁nat
- ▁sl
- ▁num
- av
- ways
- ▁God
- stem
- ▁ac
- ▁att
- ▁ev
- ▁def
- llow
- ▁str
- lect
- ars
- ▁cr
- ▁Is
- olog
- les
- oy
- ▁ask
- ▁inc
- body
- ▁ent
- ▁pol
- ness
- ix
- ▁why
- onna
- ▁ear
- ▁tak
- ▁Un
- ited
- mun
- li
- ute
- ract
- ▁dec
- uro
- ▁mak
- ▁fin
- ween
- ▁No
- arch
- ▁bec
- gan
- old
- cy
- ▁big
- ▁For
- ren
- als
- und
- ▁Al
- ▁All
- ss
- ows
- ▁mod
- ock
- ▁id
- ism
- cus
- ▁gl
- ably
- ▁ass
- ▁car
- ata
- ppen
- led
- ▁sim
- ▁mon
- ics
- ▁giv
- cept
- ▁Mr
- pan
- ▁pub
- ▁eff
- ▁How
- ps
- vern
- end
- hip
- iew
- ope
- ▁An
- ▁She
- ▁Com
- ee
- ures
- ell
- ouse
- cond
- king
- oc
- ues
- ever
- ▁To
- clud
- ▁ins
- ▁exp
- ▁old
- ▁mem
- ▁ref
- ▁tra
- ▁far
- ave
- rat
- ▁sur
- ruct
- rib
- duct
- uff
- ▁met
- ▁sch
- ince
- ▁run
- ense
- ▁cle
- ▁==
- mon
- ize
- ▁ord
- blem
- tin
- ▁Let
- ner
- ond
- its
- ▁cor
- land
- ▁cur
- ▁Re
- ▁bus
- ▁uh
- air
- ote
- ants
- ason
- ric
- ▁el
- ▁cer
- nce
- ▁fam
- ▁cap
- uck
- ool
- ried
- ▁cou
- ▁fun
- ▁wom
- ▁hum
- ▁ty
- ▁ap
- ike
- ▁few
- oney
- ▁inf
- ont
- ese
- ook
- gy
- uth
- ulat
- ieve
- ized
- ross
- ▁ple
- ▁um
- ▁val
- ▁equ
- ▁lea
- ▁lar
- ah
- eral
- ▁ed
- ared
- lish
- arn
- ds
- esn
- ▁iss
- ▁ca
- ted
- ices
- ▁wee
- ash
- ▁top
- ten
- up
- ts
- gin
- con
- ari
- ▁opp
- osed
- ▁eas
- ▁ext
- gg
- az
- ▁Fr
- ideo
- izat
- ▁men
- ▁mom
- ▁ret
- tty
- rist
- ▁gra
- alth
- ef
- ▁det
- ax
- ▁mat
- chn
- ern
- peri
- ▁bre
- ▁Sh
- sw
- erat
- ▁sit
- ters
- ale
- man
- ▁sol
- ork
- ▁adv
- ety
- ▁vis
- ▁med
- uc
- less
- ▁unt
- gram
- ets
- ists
- ▁ey
- ▁col
- imes
- ▁law
- ▁pri
- sid
- ▁On
- ▁mot
- ield
- ▁Do
- ▁At
- ages
- amp
- ▁art
- miss
- ▁sk
- alf
- pr
- ier
- ▁beh
- ▁Yes
- ural
- ime
- ▁wa
- oks
- bers
- ger
- ient
- ries
- '...'
- ▁che
- ▁Br
- ird
- ▁Ar
- ▁war
- inat
- ▁My
- ital
- wh
- med
- ▁pur
- ully
- ▁One
- ▁rat
- ines
- ▁Of
- io
- ▁loc
- ret
- ctor
- ▁leg
- stit
- ined
- ught
- ▁dur
- ▁es
- vent
- aj
- ▁bro
- ▁saw
- ▁sec
- ream
- ▁pop
- reen
- ▁Ind
- els
- ▁yet
- ired
- ▁sw
- tro
- oup
- most
- pean
- eds
- ush
- oh
- ▁Se
- ▁tea
- ann
- ilit
- err
- pend
- ton
- ased
- ▁aff
- ▁mor
- ▁dra
- put
- ▁dr
- ins
- uat
- nect
- cri
- outh
- ▁ra
- ▁pay
- ms
- ▁av
- bs
- ling
- ▁De
- ▁Or
- ove
- ▁Can
- ▁eng
- ames
- ided
- ▁Go
- mitt
- ode
- ▁cre
- par
- ides
- pos
- ▁fav
- ▁air
- ▁New
- ▁bad
- ▁six
- vat
- ▁pat
- not
- ▁di
- rop
- ral
- orn
- ▁par
- cing
- ▁aw
- orts
- ox
- ▁yes
- cuss
- eng
- ives
- erms
- ▁job
- mand
- ying
- ▁occ
- aps
- ases
- ▁Not
- rent
- ency
- att
- ised
- vice
- ▁Eng
- ▁est
- oked
- ▁Q
- iron
- idd
- me
- unch
- ane
- ▁z
- br
- arts
- ▁fat
- ery
- anks
- ▁jo
- ▁mar
- aw
- ott
- ards
- ▁oh
- ians
- ▁sci
- row
- unt
- ury
- ▁abs
- ergy
- ▁Z
- ump
- ▁Am
- ened
- angu
- ▁Pro
- icat
- itch
- ▁dri
- iat
- ▁
- e
- t
- o
- a
- 'n'
- i
- s
- r
- h
- l
- d
- u
- c
- m
- 'y'
- g
- w
- f
- p
- ','
- .
- b
- v
- k
- ''''
- I
- T
- A
- S
- x
- W
- j
- C
- B
- M
- '?'
- H
- O
- '0'
- P
- q
- 'Y'
- 'N'
- L
- D
- '1'
- E
- G
- z
- F
- R
- '-'
- '2'
- J
- U
- '9'
- K
- '5'
- '3'
- V
- '='
- '4'
- '8'
- '6'
- '7'
- '!'
- '%'
- ':'
- Q
- Z
- $
- X
- '"'
- '&'
- '*'
- /
- £
- +
- €
- _
- ^
- ¥
target: nemo.collections.asr.models.multitalker_asr_models.EncDecMultiTalkerRNNTBPEModel
nemo_version: 2.6.0rc0
