import createVietasrModule from "../dist/vietasr-core.js";
import { MODEL_BASE_URL } from "../dist/model-config.js";

// onnxruntime-web is resolved lazily inside Pipeline.create() instead of with a
// static `import` so this module graph carries no bare specifier. That lets the
// file load inside a Web Worker (which has no import map) when the caller passes
// an explicit `ortModuleUrl`; bundler/npm users get the default "onnxruntime-web".
let ort = null;

const INPUT_FRAMES = 43;
const FEATURE_DIM = 80;
const OUTPUT_FRAMES = 10;
const NUM_LAYERS = 12;
const ATT_HEADS = 4;
const ATT_CACHE_LEN = 40;
const ATT_CACHE_DIM = 224;
const CNN_CACHE_W = 448;
const CNN_CACHE_H = 30;

// The vietasr model (~67 MB) is fetched at runtime, not bundled, so the npm
// package stays small. MODEL_BASE_URL is generated by build-wasm.sh and pins
// the model to this release on jsDelivr; override via Pipeline.create({modelUrl}).
async function loadAsset(name, baseUrl) {
    const res = await fetch(new URL(name, baseUrl));
    if (!res.ok) throw new Error(`fetch ${name}: ${res.status}`);
    return new Uint8Array(await res.arrayBuffer());
}

async function sha256Hex(bytes) {
    if (!globalThis.crypto?.subtle) return null;
    const digest = await globalThis.crypto.subtle.digest("SHA-256", bytes);
    return [...new Uint8Array(digest)]
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("");
}

/** Fetch and reassemble the chunked model + vocab from `baseUrl`. */
async function loadModel(baseUrl) {
    const manifest = JSON.parse(
        new TextDecoder().decode(await loadAsset("chunks.json", baseUrl)));

    const model = new Uint8Array(manifest.total_size);
    let offset = 0;
    for (const chunk of manifest.chunks) {
        const part = await loadAsset(chunk.name, baseUrl);
        if (part.length !== chunk.size) {
            throw new Error(
                `chunk ${chunk.name}: got ${part.length}, expected ${chunk.size}`);
        }
        model.set(part, offset);
        offset += part.length;
    }
    if (offset !== manifest.total_size) {
        throw new Error(
            `reassembled model size ${offset}, expected ${manifest.total_size}`);
    }
    const got = await sha256Hex(model);
    if (got && manifest.sha256 && got !== manifest.sha256) {
        throw new Error(`model sha256 mismatch: ${got} != ${manifest.sha256}`);
    }

    const unitsText = new TextDecoder().decode(
        await loadAsset("vocab.txt", baseUrl));
    return { encoderModel: model, unitsText };
}

/**
 * Browser Vietnamese ASR pipeline.
 *
 * Architecture: the DSP front-end (fbank, CTC prefix beam search,
 * BPE detokenize) runs in WebAssembly compiled from the shared C++ core.
 * The streaming Conformer encoder runs via onnxruntime-web. JS orchestrates
 * the two and carries the att/cnn caches between chunks.
 */
export class Pipeline {
    constructor(wasm, session, unitsText) {
        this.wasm = wasm;
        this.session = session;
        this.unitsText = unitsText;
        this.encoderOffset = 0;
        this.attCache = new Float32Array(
            NUM_LAYERS * ATT_HEADS * ATT_CACHE_LEN * ATT_CACHE_DIM);
        this.cnnCache = new Float32Array(NUM_LAYERS * CNN_CACHE_W * CNN_CACHE_H);
    }

    /**
     * @param {object} [options]
     * @param {string} [options.unitsText] pre-loaded vocab (skips model fetch)
     * @param {ArrayBuffer|Uint8Array} [options.encoderModel] pre-loaded ONNX (skips model fetch)
     * @param {string} [options.modelUrl] base URL for the model assets
     *        (chunks.json, vocab.txt, model.onnx.part*); defaults to the
     *        release pinned on jsDelivr.
     * @param {string} [options.ortModuleUrl] explicit URL to the onnxruntime-web
     *        ESM module. Required in a Web Worker (no import map); omit it to
     *        use the bare "onnxruntime-web" specifier (bundler/npm).
     * @param {string} [options.ortWasmPaths] directory holding onnxruntime-web's
     *        own .wasm files; sets ort.env.wasm.wasmPaths when provided.
     */
    static async create(options = {}) {
        if (!ort) {
            // Keep the bare specifier a plain string literal so bundlers can
            // still statically resolve onnxruntime-web for npm consumers; the
            // dynamic-URL branch is only taken with an explicit ortModuleUrl.
            const mod = options.ortModuleUrl
                ? await import(options.ortModuleUrl)
                : await import("onnxruntime-web");
            ort = mod.InferenceSession ? mod : (mod.default ?? mod);
        }
        if (options.ortWasmPaths) ort.env.wasm.wasmPaths = options.ortWasmPaths;

        const wasm = await createVietasrModule();

        let unitsText = options.unitsText;
        let encoderBuffer = options.encoderModel;
        if (!unitsText || !encoderBuffer) {
            const fetched = await loadModel(options.modelUrl || MODEL_BASE_URL);
            unitsText = unitsText || fetched.unitsText;
            encoderBuffer = encoderBuffer || fetched.encoderModel;
        }

        const initStatus = wasm.ccall(
            "vietasr_wasm_init", "number", ["string"], [unitsText]);
        if (initStatus !== 0) {
            throw new Error(`wasm init failed: ${initStatus}`);
        }

        const modelBytes = encoderBuffer instanceof Uint8Array
            ? encoderBuffer : new Uint8Array(encoderBuffer);
        const session = await ort.InferenceSession.create(
            modelBytes,
            { executionProviders: ["wasm"] });

        return new Pipeline(wasm, session, unitsText);
    }

    reset() {
        this.wasm.ccall("vietasr_wasm_reset", null, [], []);
        this.encoderOffset = 0;
        this.attCache.fill(0);
        this.cnnCache.fill(0);
    }

    /**
     * Transcribe a complete audio clip.
     * @param {Float32Array} pcm  audio samples in [-1, 1]
     * @param {number} sampleRate
     * @returns {Promise<string>}
     */
    async transcribe(pcm, sampleRate = 16000) {
        this.reset();
        await this._feed(pcm, sampleRate);
        await this._drain();
        return this._transcript();
    }

    /**
     * Begin a streaming session. Clears decoder + encoder state. Call once
     * before the first pushStream().
     */
    startStream() {
        this.reset();
    }

    /**
     * Feed one chunk of live audio. Runs every full encoder window currently
     * available and leaves the partial tail buffered for the next call.
     * @param {Float32Array} pcm  audio samples in [-1, 1]
     * @param {number} sampleRate
     * @returns {Promise<string>} the transcript so far (normalized partial)
     */
    async pushStream(pcm, sampleRate = 16000) {
        const wasm = this.wasm;
        await this._feed(pcm, sampleRate);
        while (wasm.ccall("vietasr_wasm_frames_ready", "number", [], [])
            >= INPUT_FRAMES) {
            await this._runChunk(INPUT_FRAMES);
        }
        return this._transcript();
    }

    /**
     * Flush the buffered tail frames and return the final transcript.
     * @returns {Promise<string>}
     */
    async finishStream() {
        const tail = this.wasm.ccall(
            "vietasr_wasm_frames_ready", "number", [], []);
        if (tail > 0) await this._runChunk(tail);
        return this._transcript();
    }

    async _feed(pcm, sampleRate) {
        const wasm = this.wasm;
        const bytes = pcm.length * 4;
        const ptr = wasm._malloc(bytes);
        wasm.HEAPF32.set(pcm, ptr >> 2);
        wasm.ccall("vietasr_wasm_accept_pcm", "number",
            ["number", "number", "number"], [ptr, pcm.length, sampleRate]);
        wasm._free(ptr);
    }

    async _drain() {
        const wasm = this.wasm;
        while (true) {
            const ready = wasm.ccall("vietasr_wasm_frames_ready", "number", [], []);
            if (ready < INPUT_FRAMES) break;
            await this._runChunk(INPUT_FRAMES);
        }
        const tail = wasm.ccall("vietasr_wasm_frames_ready", "number", [], []);
        if (tail > 0) {
            await this._runChunk(tail);
        }
    }

    async _runChunk(nFrames) {
        const wasm = this.wasm;
        const featPtr = wasm.ccall("vietasr_wasm_pop_features", "number",
            ["number"], [nFrames]);
        const features = new Float32Array(INPUT_FRAMES * FEATURE_DIM);
        const popped = wasm.HEAPF32.subarray(
            featPtr >> 2, (featPtr >> 2) + nFrames * FEATURE_DIM);
        features.set(popped);

        const feeds = {
            chunk: new ort.Tensor("float32", features, [1, INPUT_FRAMES, FEATURE_DIM]),
            offset: new ort.Tensor("int64",
                BigInt64Array.from([BigInt(this.encoderOffset)]), [1, 1]),
            att_cache: new ort.Tensor("float32", this.attCache,
                [1, NUM_LAYERS, ATT_HEADS, ATT_CACHE_LEN, ATT_CACHE_DIM]),
            cnn_cache: new ort.Tensor("float32", this.cnnCache,
                [1, NUM_LAYERS, CNN_CACHE_W, CNN_CACHE_H]),
        };

        const out = await this.session.run(feeds);
        const logits = out.output;
        const vocab = logits.dims[logits.dims.length - 1];
        const outFrames = logits.dims[logits.dims.length - 2];

        const logitsData = logits.data;
        const lbytes = logitsData.length * 4;
        const lptr = wasm._malloc(lbytes);
        wasm.HEAPF32.set(logitsData, lptr >> 2);
        wasm.ccall("vietasr_wasm_decode_logits", null,
            ["number", "number", "number"], [lptr, outFrames, vocab]);
        wasm._free(lptr);

        this.attCache = out.r_att_cache.data;
        this.cnnCache = out.r_cnn_cache.data;
        this.encoderOffset += OUTPUT_FRAMES;
    }

    _transcript() {
        return this.wasm.ccall("vietasr_wasm_transcript", "string", [], []);
    }
}

export default { Pipeline };
